name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: login to docker hub
        run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB}} --password-stdin
      - name: Build docker image
        run: docker build -t casseli/nodebacktprod .
      - name: Publish image to docker hub
        run: docker push casseli/nodebacktprod:latest


  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Delete old container
        run: sudo docker rm -f node-server
      - name: Delete old image
        run: sudo docker rmi -f casseli/nodebacktprod
      - name: Pull image from docker hub
        run: sudo docker pull casseli/nodebacktprod:latest
      - name: Run docker container
        run: sudo docker run -d -p 4000:4000 --name node-server -v "$PWD/.env:/app/.env" --network mi_red casseli/nodebacktprod:latest
